---
title: "Luka changes"
format: html
editor: visual
---

UVOD

Institucionalni investitori, poput mirovinskih i državnih fondova, često nastoje održavati stalnu strukturu portfelja. Takvi fondovi, osim što imaju jasno definirane investicijske politike, podliježu i zakonskim ograničenjima definiranima u xxx i Pravilniku o dozvoljenim ulaganjima i dodatnim ograničenjima ulaganja obveznog mirovinskog fonda, koji definira dozvoljene udjele (i.e. maksimalna ulaganja) ulaganja u pojedine klase imovine (npr. dionice, obveznice, nekretnine). Povećanje vrijednosti jedne klase imovine u portfelju, takve će fondove primorati na prodaju te klase imovine i kupnju druge klase imovine čija je vrijednost rasla manje, u cilju pridržavanja zadanih udjela u portfelju. Na taj način fondovi sustavno kupuju „gubitnike“ i prodaju „dobitnike“, što može imati utjecaj na agregatna kretanja dioničkog i obvezničkog tržišta. U ovome radu analizira se mogući utjecaj takvog rebalansiranja mirovinskih, državnih i drugih institucionalnih fondova na ukupna tržišna kretanja na Zagrebačkoj burzi.

Rebalansiranje investicijskog portfelja institucionalnih investitora obično se provodi sukladno graničnom i kalendarskom principu (Doe, 2025). Kod graničnog principa, fondovi provode rebalansiranje samo kad udio pojedine imovine prijeđe unaprijed određeni prag, kako bi se ublažili transakcijski troškovi. S druge strane, kalendarsko pravilo podrazumijeva rebalansiranje u jednakim vremenskim intervalima – obično mjesečno, a rjeđe tromjesečno ili dnevno. Ovaj rad usredotočuje se na kalendarski efekt, odnosno utjecaj rebalansiranja krajem mjeseca na prinose dioničkih i obvezničkih indeksa. Pretpostavka je da će se kod intenzivnog rebalansiranja krajem mjeseca povećati prinosi onih klasa imovine koje su u prvoj polovici mjeseca ostvarile slabije rezultate te, obrnuto, sniziti prinosi onih koje su rasle. Osim toga, potreba za novčanim tokovima na kraju mjeseca može biti dodatan motiv mjesečnog rebalansiranja (Etula i sur., 2020). Točno vrijeme trgovanja idealno bi bilo ustanoviti na temelju dnevnih podataka o rebalansiranju, no kako takvi podaci nisu javno dostupni, u ovome se radu pretpostavlja mjesečno rebalansiranje. Doprinos ovoga rada očituje se u nekoliko aspekata. Prvo, istraživanje pruža uvid u odnos mjesečnog rebalansnog ciklusa i kretanja dioničkog i obvezničkog tržišta Zagrebačke burze. Drugo, istraživanje koristi sveobuhvatni metodološki okvir koji kombinira deskriptivnu analizu, statističku procjenu te simuliranu investicijsku strategiju koja ispituje je li moguće ostvariti dodatni prinos i poboljšani omjer prinosa i rizika kupnjom „podcijenjene“ imovine neposredno prije kraja mjeseca. U cilju robusnosti je provedena analiza i utjecaja kalendarskog pomaka (na početku ili sredini mjeseca te pri različitim intervalima od kraja mjeseca) na rezultate simulirane investicijske strategije. Treće, često rebalansiranje nosi znatne transakcijske troškove, koji uključuju brokerske naknade, bid-ask spreadove i tržišni utjecaj trgovanja, što može negativno utjecati na profitabilnost fondova. Dokaz o postojanju kalendarskog efekta stoga ukazuje na pretjerane troškove i općenito, preispitivanje politike rebalansiranja. Ovaj je nalaz od važnosti i za druge institucionalne investitore koji shodno mogu uskladiti svoje strategije, primjerice kupnjom dionica pri kraju mjeseca ako su se u prvome dijelu pokazale slabije. Nakon uvoda slijedi pregled literature o rebalansiranju, kalendarskim efektima i njihovim tržišnim učincima. Zatim se opisuju podatci upotrijebljeni u istraživanju i definira korištena metodologija. Empirijski dio rada donosi rezultate regresijske analize i simulirane investicijske strategije, dok se ključni nalazi i implikacije sažimaju u zaključnom dijelu.

LITERATURA

Važnost kalendarskog rebalansiranja u portfeljima institucionalnih investitora potvrđena je u nizu teorijskih i empirijskih istraživanja. Sa teoretskog je aspekta kalendarsko rebalansiranje moguće promatrati na dva načina: optimizacijske modele portfelja i bihevioralnu teoriju. U prvome se redu ističu modeli dinamičkog programiranja, stohastičkog programiranja i Markovljevih procesa (Sun i sur., 2004a; Sun i sur., 2004b; Sun i sur., 2006), prema kojima se optimalno raspoređuje imovina u unaprijed zadanom vremenskom intervalu. Pri tome se, uz same prinose, uzimaju u obzir i transakcijski troškovi te volatilnost tržišta. Ovdje je posebno zanimljiv koncept „rebalance timing luck“ (Hoffstein i sur., 2020a; Hoffstein i sur., 2020d), koji pokazuje da se ukupni prinos portfelja može bitno razlikovati ovisno o konkretnoj točki u mjesecu ili godini kada se rebalans provodi. S druge strane, bihevioralni pristup specifične kalendarske efekte objašnjava teorijama poput „window dressing“, „performance chasing“ ili „compensation-driven behavior“ (Bildersee i Kahn, 1987; Ng i Wang, 2004; Chan i Covrig, 2009; Jones, 2016) . Primjerice, prema „window dressing“ teoriji upravitelji fondova potkraj izvještajnog perioda kupuju dionice koje izgledaju atraktivno na tržištu, a prodaju manje atraktivne (Bildersee i Kahn, 1987). Slična obrazloženja koriste se i kod „risk shifting“ ili „performance chasing“ teorija, gdje se alokacija portfelja prilagođava sukladno prethodnim kretanjima prinosa i sklonosti fond menadžera prema dobitnim dionicama, odnosno razini rizika prije kraja godine (Ng i Wang, 2004; Chan i Covrig, 2009). Empirijski rezultati uglavnom potvrđuju postojanje određenih kalendarskih obrazaca i njihovog utjecaja na tržišna kretanja. Madhavan (2001) i Chinco i Sammon (2021) izvješćuju o značajnom rastu volumena trgovanja na dan rekompozicije velikih burzovnih indeksa, a pritom se javljaju i kratkoročne, a ponekad i trajne, cjenovne distorzije. Sličan učinak zabilježen je kod rekompozicije robnih indeksa, gdje su zabilježeni visoki (iznadprosječni) prinosi koji se relativno brzo vraćaju prema uobičajenoj razini (Yan i sur., 2020). Nadalje, kod sezonskih uzoraka trgovanja više je radova potvrdilo „turn-of-the-year“ efekte, odnosno pojačana prodavanja gubitnika i kupovanja „dobitnika“ neposredno prije ili nakon završetka godine (Ng i Wang, 2004; Cuny i sur., 1998). U nekim su slučajevima prepoznati i kvartalni efekti. Sias (2007) pronalazi veće momentum profite u mjesecima koji zatvaraju kvartal, naročito u prosincu. Athanassakos (2021) pak upućuje na cikličke sezonske fluktuacije u kanadskim financijskim tržištima, s osobito visokim prinosima dionica u razdoblju od studenoga do travnja. Sa jedne strane, rezultati istraživanja upućuju na konsenzus oko postojanja periodične prilagodbe portfelja, bilo na mjesečnoj, kvartalnoj ili godišnjoj osnovi i njihovog utjecaja na cijene i obujam trgovanja. Sa druge strane, nejasnoće i varijacije u politikama rebalansiranja institucionalnih investitora proizlaze iz kombinacije optimizacijskih i bihevioralnih čimbenika. Bams i sur. (2016) tako pokazuju da su mirovinski fondovi skloni asimetričnom rebalansiranju u cilju upravljanja rizikom, dok Cuny i sur. (1998) i Ng i Wang (2004) govore o nastojanju profesionalnih investitora da se krajem godine približe referentnom tržišnom prinosu („benchmark mimicking“) i time izbjegnu nepovoljne procjene rezultata. U globalnom kontekstu, određena istraživanja (Jones, 2016) potvrđuju da se veliki institucionalni vlasnici ponekad ponašaju pro-ciklično, tj. intenziviraju kupnje ili prodaje na temelju prethodnih trendova, što može pojačati kolebanja na tržištu. Razlika u nalazima pojedinih istraživanja često ovisi o tome koliko je tržište razvijeno, koliku ulogu imaju konkretni zakonski i regulatorni okviri te o vrsti institucionalnog investitora. Uz to, uloga „sunshine tradinga“, gdje je rebalans vidljiv i očekivan, može dovesti do strategija „front-run“ trgovanja od strane drugih sudionika, što dodatno komplicira cjenovne učinke (Yan i sur., 2020).
